### ISSUE TITLE
Fix generate pipline

### ISSUE THREAD

**Issue by edd** [vegaprotocol/networks#125]
# Problem
When someone opens a PR on this repo, [the action generate-networks.yml](https://github.com/vegaprotocol/networks/blob/master/.github/workflows/generate-networks.yml) will recreate `networks.json` and commit it in the same PR. There are a couple of issues with this approach:

- In the Github UI, the commit appears to come from the original author. In fact, it is made by an action
- Triggering by `cron` feels like the wrong trigger. Better would be any commit on `main`. All changes *should* be through a PR, but commits to `main` would cover the case where someone makes a change directly

## Secondary problem
[vegawallet-desktop](https://github.com/vegaprotocol/vegawallet-desktop) relies on a property, `explorerUrl`, existing in `networks.json`. This is not added by the [node script that generates the networks.json](https://github.com/vegaprotocol/networks/blob/master/scripts/generate-json.js). It should be.

# Tasks
Let's fix the first 3 problems, unless it is just as easy to do this in a neater way.
- [x] Change trigger for action to be commits on the `master`
- [x] Ensure that the commit triggered is clearly automated and not by the previous committer. 
- [x] Update `generate-json.js` to add `explorerUrl`. This can be hardcoded, or read from a file within the folder.

# Things that should remain true
- [x] `networks.json` should be in the root of the repository, as this is where some clients expect to fetch it from
- [x] `networks.json` should contain an `explorerUrl` for as many networks as it can

# Original ticket
              > @jeremyletang it's happened again and it's not me 😮
> 
> > [@github-actions[bot]](https://github.com/github-actions) pushed 1 commit.
> > [9be155e](https://github.com/vegaprotocol/networks/commit/9be155e09858088e30191d79a35091da31f464a1) generate networks

Alright, looking into that.

_Originally posted by @jeremyletang in https://github.com/vegaprotocol/networks/issues/123#issuecomment-1428060139_
